# Generated by Django 2.2.6 on 2020-04-20 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Oxygen_Supplementation_Initiated', models.CharField(default='null', max_length=20)),
                ('Oxygen_Supplementation_Stopped', models.CharField(default='null', max_length=20)),
                ('Bag_Mask_Initiated', models.CharField(default='null', max_length=20)),
                ('Bag_Mask_Stopped', models.CharField(default='null', max_length=20)),
                ('LMA_Initiated', models.CharField(default='null', max_length=20)),
                ('LMA_Achieved', models.CharField(default='null', max_length=20)),
                ('LMA_Stopped', models.CharField(default='null', max_length=20)),
                ('ETT_Initiated', models.CharField(default='null', max_length=20)),
                ('ETT_Achieved', models.CharField(default='null', max_length=20)),
                ('ETT_Stopped', models.CharField(default='null', max_length=20)),
                ('Difficult_Airway_Initiated', models.CharField(default='null', max_length=20)),
                ('Difficult_Airway_Achieved', models.CharField(default='null', max_length=20)),
                ('Difficult_Airway_Stopped', models.CharField(default='null', max_length=20)),
                ('Surgical_Airway_Initiated', models.CharField(default='null', max_length=20)),
                ('Surgical_Airway_Achieved', models.CharField(default='null', max_length=20)),
                ('Surgical_Airway_Stopped', models.CharField(default='null', max_length=20)),
                ('Spontaneous_Breathing', models.CharField(default='null', max_length=20)),
                ('Assisted_Breathing', models.CharField(default='null', max_length=20)),
                ('Right_Chest', models.CharField(default='null', max_length=20)),
                ('Left_Chest', models.CharField(default='null', max_length=20)),
                ('Lip_Color', models.CharField(default='null', max_length=20)),
                ('Nail_Color', models.CharField(default='null', max_length=20)),
                ('Cap_Refill', models.CharField(default='null', max_length=20)),
                ('PIV_Count', models.CharField(default='0', max_length=20)),
                ('Central_Line', models.CharField(default='no', max_length=20)),
                ('Intraosseous_Line', models.CharField(default='no', max_length=20)),
                ('IV_Fluid_Amount', models.CharField(default='none', max_length=20)),
                ('Type_Cross', models.CharField(default='null', max_length=20)),
                ('Transfused_PRBC', models.CharField(default='no', max_length=20)),
                ('Massive_Transfusion', models.CharField(default='no', max_length=20)),
                ('Pupils_Equal', models.CharField(default='null', max_length=20)),
                ('Pupils_Round', models.CharField(default='null', max_length=20)),
                ('Pupils_Reactive', models.CharField(default='null', max_length=20)),
                ('Pupil_Size_Right', models.CharField(default='null', max_length=20)),
                ('Pupil_Size_Left', models.CharField(default='null', max_length=20)),
                ('Moves_Extremities', models.CharField(default='null', max_length=20)),
                ('ETCO2', models.CharField(default='null', max_length=20)),
                ('GCS', models.CharField(default='null', max_length=20)),
                ('GCS_Motor', models.CharField(default='null', max_length=20)),
                ('GCS_Verbal', models.CharField(default='null', max_length=20)),
                ('GCS_Eye', models.CharField(default='null', max_length=20)),
                ('Shock_Level', models.CharField(default='null', max_length=20)),
                ('HR', models.CharField(default='null', max_length=20)),
                ('BP', models.CharField(default='null', max_length=20)),
                ('GCS_History', models.CharField(default='null', max_length=20)),
                ('ETCO2_History', models.CharField(default='null', max_length=20)),
                ('Shock_History', models.CharField(default='null', max_length=20)),
                ('HR_History', models.CharField(default='null', max_length=20)),
                ('BP_History', models.CharField(default='null', max_length=20)),
                ('Patient_Age', models.CharField(default='null', max_length=20)),
                ('Patient_Weight', models.CharField(default='null', max_length=20)),
                ('Patient_History', models.CharField(default='null', max_length=20)),
                ('Patient_AddInfo', models.CharField(default='null', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
