# Generated by Django 2.2.6 on 2020-04-08 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('ETCO2', models.CharField(default='not recorded', max_length=20)),
                ('GCS', models.CharField(default='null', max_length=20)),
                ('Shock_Level', models.CharField(default='null', max_length=20)),
                ('HR', models.CharField(default='null', max_length=20)),
                ('BP', models.CharField(default='null', max_length=20)),
                ('Patient_Age', models.CharField(default='null', max_length=20)),
                ('Type_and_Cross', models.CharField(default='none', max_length=20)),
                ('Lip_Color', models.CharField(default='null', max_length=20)),
                ('Nail_Bed_Color', models.CharField(default='null', max_length=20)),
                ('Cap_Refill_Time', models.CharField(default='null', max_length=20)),
                ('HR_Display', models.CharField(default='null', max_length=20)),
                ('BP_Display', models.CharField(default='null', max_length=20)),
                ('Shock_Level_Display', models.CharField(default='null', max_length=20)),
                ('Right_Chest_Rise_Breath_Sounds', models.CharField(default='null', max_length=20)),
                ('Left_Chest_Rise_Breath_Sounds', models.CharField(default='null', max_length=20)),
                ('Massive_Transfusion_Protocol', models.CharField(default='null', max_length=20)),
                ('Transfusion_PRBC', models.CharField(default='null', max_length=20)),
                ('ETT', models.CharField(default='null', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
