# Generated by Django 2.2.6 on 2020-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ETCO2', models.CharField(default='not recorded', max_length=20)),
                ('Lip_Color', models.CharField(default='null', max_length=20)),
                ('Nail_Bed_Color', models.CharField(default='null', max_length=20)),
                ('Cap_Refill_Time', models.CharField(default='null', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
