# Generated by Django 2.2.6 on 2019-10-23 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='timeEnded',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='A_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='B_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='C_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='D_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='E_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='timeStarted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
