# Generated by Django 2.2.6 on 2020-04-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date_created',
        ),
    ]
