# Generated by Django 2.2.6 on 2020-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0002_auto_20200218_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default='SessionDefault', max_length=30),
        ),
    ]
