# Generated by Django 2.2.6 on 2020-04-08 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0002_remove_session_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
