# Generated by Django 2.2.6 on 2020-04-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0002_auto_20200420_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='IV_Fluid_Amount',
        ),
        migrations.RemoveField(
            model_name='session',
            name='Patient_AddInfo',
        ),
        migrations.RemoveField(
            model_name='session',
            name='Patient_History',
        ),
        migrations.AddField(
            model_name='session',
            name='Abdomen_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Assisted_Breathing_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Back_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Bag_Mask_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Bag_Mask_RR',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='CV_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Cap_Refill_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Central_Line_History',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Difficult_Airway_Adjunct',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Difficult_Airway_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='ETT_Depth',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='ETT_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='ETT_RR',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Ears_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Exposure_History',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Eyes_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='GCS_Eye_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='GCS_Motor_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='GCS_Verbal_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='GU_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Head_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='IVF_History',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='IVF_Total',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Intraosseous_Line_History',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Jugular_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='LLE_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='LMA_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='LUE_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Left_Chest_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Lip_Color_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Lungs_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Massive_Transfusion_History',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='MidFace_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Moves_Extremities_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Nail_Color_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Oxygen_Supplementation_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='PIV_History',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Patient_Mechanism_Injury',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Patient_Pre_Arrival',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Pelvis_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Pupil_Left_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Pupil_Right_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Pupils_Equal_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Pupils_Reactive_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Pupils_Round_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='RLE_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='RUE_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Rectal_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Right_Chest_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Skin_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Spontaneous_Breathing_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Surgical_Airway_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Trachea_Abnormality',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Transfused_PRBC_History',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Type_Cross_History',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='BP',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='ETCO2',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='GCS',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='GCS_Eye',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='GCS_Motor',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='GCS_Verbal',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='HR',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='Moves_Extremities',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='Pupil_Size_Left',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='Pupil_Size_Right',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='Pupils_Equal',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='Pupils_Reactive',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='Pupils_Round',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='Shock_Level',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
