# Generated by Django 2.2.6 on 2020-03-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0002_auto_20200318_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='Patient_Age',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Type_and_Cross',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
