# Generated by Django 2.2.6 on 2020-03-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0003_auto_20200320_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='Left_Chest_Rise_Breath_Sounds',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Right_Chest_Rise_Breath_Sounds',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
