# Generated by Django 2.2.6 on 2020-03-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0004_auto_20200320_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='BP',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='HR',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Massive_Transfusion_Protocol',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Shock_Level',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Transfusion_PRBC',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
