# Generated by Django 2.2.6 on 2020-03-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0004_remove_session_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='author',
        ),
        migrations.RemoveField(
            model_name='session',
            name='content',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date_created',
        ),
        migrations.AddField(
            model_name='session',
            name='Cap_Refill_Time',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Lip_Color',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Nail_Bed_Color',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
