# Generated by Django 2.2.6 on 2020-03-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0005_auto_20200321_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='BP_Display',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='ETT',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='GCS',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='HR_Display',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='Shock_Level_Display',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
